### ISSUE TITLE
Accuracy of each fold

### ISSUE THREAD

**Issue by AyaneAI** [kamalesh0406/Audio-Classification#11]
Sorry to disturb you. I fork your code and try to use 'resnet' to predict samples in dataset 'UrbanSound8k'. However, Accuracy of the first fold is 76.9, which is far below 84.76%[1], so I want to know if it is normal and hope if you could make your result of each fold public. Look forward to your reply.

[1] Palanisamy, Kamalesh, et al. “Rethinking CNN Models for Audio Classification.” ArXiv Preprint ArXiv:2007.11154, 2020.

**Comment by kamalesh0406** [comment]
Hi, 
I will try to find the results for the first fold and post them here. But anyways, I would suggest you try to run the model across all the folds and take the average of the accuracy. I do remember that the scores on some of the folds might be less then the average score.

**Comment by AyaneAI** [comment]
Thanks for your help!! I would take your advice, then show the result of each fold in this issue.

**Comment by AyaneAI** [comment]
Hi, I have a question with K-fold in this task.
I want to confirm whether the best accuracy of my model is used as final accuracy of each fold, but I can not find related codes in the project.

**Comment by AyaneAI** [comment]
The result of the model ResNet trained on my machine is [79.83963%, 88.51335%, 75.89189%, 84.94949%, 88.67521%, 80.80194%, 84.00954%, 79.03225%, 87.377450%, 87.93309%]. The mean accuracy of 10 fold is 83.70240, slightly lower than result in the paper(84.76%). The mean accuracy of last iteration of each fold is 79.1663%.

**Comment by kamalesh0406** [comment]
Hi, Sorry for the late response. By mean accuracy, you mean the best accuracy you can achieve with the model right? We take the mean of the best accuracy the model achieves on each fold. Since there is a bit of variance, it is expected that your results might be lower or higher than what we reported on our paper.

**Comment by AyaneAI** [comment]
Thanks for you response. My problem has been solved.
