### ISSUE TITLE
Prediction/Inference for novel data

### ISSUE THREAD

**Issue by AdolfVonKleist** [kamalesh0406/Audio-Classification#12]
Do you provide a utility/function for inference on novel data, that is, a way to apply a trained model to a previously unseen audio file?

**Comment by kamalesh0406** [comment]
Hi, I am extremely sorry for the very late reply. I suppose you could use the evaluate function in the validate.py file for inference based on any data loader that follows a similar format to one provided in the repo.

**Comment by jvaleroliet** [comment]
Hi, I'm very interested in this. To construct a function that takes one song path and do all the transformations needed. Is it possible?
