### ISSUE TITLE
train.py is running but no outputs

### ISSUE THREAD

**Issue by farahrefaai** [kamalesh0406/Audio-Classification#3]
Salam Kamalesh,

I added a print command before "with tqdm(total=len(data_loader)) as t:" and it was the last output in the console. I stopped running the file after more than 5 hours and nothing changed, unfortunately.

do you have any idea why this may happen?

Thanks a lot!!

**Comment by kamalesh0406** [comment]
Maybe it is because the model is not running on gpu can you share more details about your setup?

**Comment by farahrefaai** [comment]
No, the model is running on gpu gtx 1080 ti.

**Comment by kamalesh0406** [comment]
This is strange. Can you comment and check the size of the dataloader to see if the data is being loaded?

**Comment by kamalesh0406** [comment]
Issue closed due to lack of activity.
