### ISSUE TITLE
About the Integrated Gradients

### ISSUE THREAD

**Issue by suyuzhang** [kamalesh0406/Audio-Classification#5]
Hi,
Thanks for your contibution. I am interested in your paper and trying to run the scripts. I found you mentioned the integrated gradients results in your paper. It is amazing. Could you provide the related code? 

Thanks

**Comment by kamalesh0406** [comment]
Hi, 
Sorry for the inconvenience, I have still not made the visualization code public it is a bit dirty but I will try to do it in the coming days. However, I used the captum library, and the code in this tutorial https://captum.ai/tutorials/Resnet_TorchVision_Interpret is very similar to what I have done. I think that will help you to run the visualization. Hope this helps!

**Comment by JNaranjo-Alcazar** [comment]
Hi, was the code finally released?

Thanks in advance
