### ISSUE TITLE
Error occur when running the classification for 'UrbanSound8k' with normalization.

### ISSUE THREAD

**Issue by tjdhg456** [kamalesh0406/Audio-Classification#6]
Thank you for the great works.

When we tried to run the urbansound 8k classification tasks with augmentation, some error occured (in the fold 2).

"Padding size should be less than the dimension 2 of the samples."

It occured from the following code in "datasetaug.py".

spec = torchaudio.transforms.MelSpectrogram(sample_rate=self.sr, n_fft=self.fft, win_length=window_length, hop_length=hop_length, n_mels=self.melbins)(clip)

Is it normal? or i run in the different version of librosa?

Thank you.

**Comment by kamalesh0406** [comment]
I don't think so the version of librosa will matter much. Can you post the entire traceback for the error?

**Comment by saidkaram** [comment]
I facing a problem during pre-processing of USC dataset. the pre-processing reach to 95% and then give an error about input size like that.

**Comment by kamalesh0406** [comment]
Okay sorry for the inconvenience. Can you post the exact traceback for the error so it's easier for me to check the bug?

**Comment by saidkaram** [comment]
thank you for your reply. I have attached the screenshot. please have a look.
![usc](https://user-images.githubusercontent.com/66631242/111896765-d2991380-8a56-11eb-97b9-793ce3b0ab8e.PNG)

**Comment by saidkaram** [comment]
this error occurs during pre-processing when it almost to 95%
![image](https://user-images.githubusercontent.com/66631242/111896857-5ce17780-8a57-11eb-825f-1d67e65bf50c.png)

**Comment by AyaneAI** [comment]
I also meet this problem. Through hint of the bug, the reason is that the length of audio is too short, I solve this problem by adding zero-padding to those short audio.

**Comment by tjdhg456** [comment]
Thank you for the kindly answer. @SCUTCS-WWB can you share the fixed codes?. Thank you.

**Comment by AyaneAI** [comment]
Of course. It's my pleasure

**Comment by saidkaram** [comment]
Thank you @SCUTCS-WWB. it will be good if you share the code.

**Comment by kamalesh0406** [comment]
Thanks for fixing the error @SCUTCS-WWB . I have merged your pull request which fixes this issue. I am closing it for now.
