### ISSUE TITLE
About GPU Utilization

### ISSUE THREAD

**Issue by AyaneAI** [kamalesh0406/Audio-Classification#8]
Thanks for your great work!
I tried to run your project, but the speed of training is very slow. I find GPU Utilization is very low, only 1%. However, GPU Usage is normal about 4GB.
I don't know the reason it happened. Looking forward to your answer!!

**Comment by kamalesh0406** [comment]
Do you mean the training code or the code for extracting the spectrograms? The code for extracting spectrograms runs slow because it does not utilize the GPU much.

**Comment by AyaneAI** [comment]
I mean the training code.
It needs about 13 minutes to run a epoch.
I only modify the parameter 'num_workers' to 0 because it may cause bugs in Windows10.

**Comment by kamalesh0406** [comment]
Oh did you try checking which device the code is running on? Like by printing out the device variable.

**Comment by AyaneAI** [comment]
Yes. The device variable shows 'cuda:0'. I use a RTX 3090 to train the model.

**Comment by kamalesh0406** [comment]
Oh okay. Btw you are running the data augmentation-based code or the normal data code?

**Comment by AyaneAI** [comment]
I use the data augmentation-based code, which is initially  setted in the config file.

**Comment by kamalesh0406** [comment]
So the problem is not with the models. Data Augmentation takes time and it
is the reason why your code is running slow. If you want to run it faster,
you can try for once without data augmentation.

**Comment by AyaneAI** [comment]
Thanks for your patience!! Answer of the problem is it as you say.
I will be appreciated if it will be solved in the future.
