### ISSUE TITLE
About datasetaug 

### ISSUE THREAD

**Issue by AyaneAI** [kamalesh0406/Audio-Classification#9]
In dataloaders/datasetaug.py(line23-line29)
```python
sample = value
limits = ((-2, 2), (0.9, 1.2))

if self.mode=="train":
	pitch_shift = np.random.randint(limits[0][1], limits[0][1] + 1)
	time_stretch = np.random.random() * (limits[1][1] - limits[1][0]) + limits[1][0]
	new_audio = librosa.effects.time_stretch(librosa.effects.pitch_shift(sample, self.sr, pitch_shift), time_stretch)
```

I want to know if there is something wrong with pitch_shift?
If use `pitch_shift = np.random.randint(limits[0][1], limits[0][1] + 1)`, so pitch shift is fixed as 2.
I think we should use  `pitch_shift = np.random.randint(limits[0][0], limits[0][1] + 1)`, so pitch shift will range from -2 to 2 as we expect.

**Comment by kamalesh0406** [comment]
Yes, I am fixing this issue right now. Thanks for finding it.
